# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-17 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('szupingxie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zhaoxinbaoming',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
