# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-25 04:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pingchao', '0002_auto_20170825_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teengame1',
            name='id_card',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='teengame1',
            name='phone',
            field=models.CharField(max_length=11),
        ),
    ]
